apiVersion: apps/v1
kind: Deployment
metadata:
  name: <preffered-name>-deployment
  namespace: <preffered-name>-ns
  labels:
    app: <preffered-name>-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: <preffered-name>-deployment
  template:
    metadata:
      labels:
        app: <preffered-name>-deployment
    spec:
      containers:
      - name: <preffered-name>-deployment
        image: gcr.io/<project_name>/<preffered-image-name>:latest         
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
