apiVersion: apps/v1
kind: Deployment
metadata:
  name: gh-check-deployment
  namespace: gh-check-ns
  labels:
    app: gh-check-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gh-check-deployment
  template:
    metadata:
      labels:
        app: gh-check-deployment
    spec:
      containers:
      - name: gh-check-deployment
        image: gcr.io/anonymous-311205/ghcheck:latest         
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /login
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
