apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gh-check-ingress
  namespace: gh-check-ns
  annotations:
    kubernetes.io/ingress.global-static-ip-name: gh-check-ext-ip
    networking.gke.io/managed-certificates: gh-check-cert
spec:
  rules:
  - host: ghchecks
    http:
      paths:
        - path: "/*"
          backend:
            serviceName: gh-check-deployment-5475p
            servicePort: 80